version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
phases:
  build:
    commands:
      - APK_BASE_DIR=app/build/outputs/apk/dev/debug
      - >
        echo "Create mocked artifacts" && 
        mkdir -p ${APK_BASE_DIR} && 
        echo "hello" > ${APK_BASE_DIR}/mocked-artifact.txt
      - ls ${APK_BASE_DIR}
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  base-directory: "${APK_BASE_DIR}"
  discard-paths: yes
  files:
    - '**.txt'
  name: $(date +%Y-%m-%d).txt
#cache:
  #paths:
    # - paths 
